### ISSUE TITLE
Color scheme for .navbar-link:focus & :focus-visible

### ISSUE THREAD

**Issue by s-gbz** [codeklasse/codeklasse.de#80]
I'm not quite sure how to display .navbar-link:focus & :focus-visible.
Moreover I've tried using $primary-dark but it somehow had no effect.

I won't bother fixing this minor problem since there're more pressing matters, but it would be nice to correct this in the future. 

```scss
.navbar-link:focus {
    background-color: $primary-dark !important;
    color: #485fc7;
}
```

![image](https://user-images.githubusercontent.com/23424538/173247874-38a3af34-e756-40da-a606-72fa80f00fdf.png)
